/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.Radio.Apresentacao;

import br.edu.ifnmg.Radio.Entidade.Anunciante;
import br.edu.ifnmg.Radio.Negocio.AnuncianteBO;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author WellisonTiago
 */
public class ListarAnunciante extends javax.swing.JFrame {

    List<Anunciante> anunciantes;
    Anunciante anuncianteSelecionado = new Anunciante ();
     int linhaselecionada;
    /**
     * Creates new form ListarAnunciante
     */
    public ListarAnunciante() {
        initComponents();
        exibirDadosTabela();
    }

    private void exibirDadosTabela() {
        try {
            this.carregarListaAnunciante();
            ModeloDadosAnunciantes modelo = new ModeloDadosAnunciantes();
            tblAnunciantes.setModel(modelo);
        } catch (Exception ex) {
            Logger.getLogger(ListarAnunciante.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void carregarListaAnunciante() throws SQLException {
        AnuncianteBO anuncianteBO = new AnuncianteBO();
        anunciantes = anuncianteBO.buscarTodos();
    }

    private void exibirMensagemErro(String titulo, String mensagem) {
        titulo = "Erro ao recuperar Anunciantes";
        mensagem = "Erro desconhecido. Entre em contato com administrador";
        JOptionPane.showMessageDialog(this, titulo, mensagem, JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnListarAnunciante = new javax.swing.JInternalFrame();
        txtListarAnunciante = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnunciantes = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnListarAnunciante.setVisible(true);

        txtListarAnunciante.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        txtListarAnunciante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtListarAnunciante.setText("Anunciantes");

        tblAnunciantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAnunciantes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblAnunciantes);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/Radio/Apresentacao/imagens/icone_lixeira.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/Radio/Apresentacao/imagens/edit5.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btRelatorio.setText("Relatorio");
        btRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnListarAnuncianteLayout = new javax.swing.GroupLayout(pnListarAnunciante.getContentPane());
        pnListarAnunciante.getContentPane().setLayout(pnListarAnuncianteLayout);
        pnListarAnuncianteLayout.setHorizontalGroup(
            pnListarAnuncianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListarAnuncianteLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btEditar)
                .addGap(71, 71, 71)
                .addComponent(btRelatorio)
                .addGap(39, 39, 39))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addComponent(txtListarAnunciante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnListarAnuncianteLayout.setVerticalGroup(
            pnListarAnuncianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListarAnuncianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtListarAnunciante)
                .addGroup(pnListarAnuncianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnListarAnuncianteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btExcluir)
                        .addGap(39, 39, 39))
                    .addGroup(pnListarAnuncianteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnListarAnuncianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btRelatorio)
                            .addComponent(btEditar))
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnListarAnunciante)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnListarAnunciante)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        try {
            int linhaselecionada = this.tblAnunciantes.getSelectedRow();
            Anunciante Anuncianteselecionado = this.anunciantes.get(linhaselecionada);
            String mensagem = "Deseja excluir " + Anuncianteselecionado.getNome() + " ?";
            String titulo = "Excluir Anunciante";
            int resultado = JOptionPane.showConfirmDialog(this, mensagem, titulo, JOptionPane.YES_NO_CANCEL_OPTION);
            if (resultado == JOptionPane.YES_OPTION) {
                AnuncianteBO anuncianteBO = new AnuncianteBO();
                try {
                    anuncianteBO.excluir(Anuncianteselecionado);
                    this.exibirDadosTabela();

                } catch (SQLException e) {
                    String mensagemerro = "Houve um erro ao excluir Anunciante";
                    String tituloerro = "Erro excluir Anunciante";
                    this.exibirMensagemErro(mensagemerro, tituloerro);
                }
            } else if (resultado == JOptionPane.NO_OPTION) {

            }
        } catch (ArrayIndexOutOfBoundsException aiobe) {
            String mensagem = "Nenhum Anunciante selecionado";
            String titulo = "Erro";
            exibirMensagemErro(mensagem, titulo);
        } finally {
            this.exibirDadosTabela();
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
      try {
            AnuncianteBO anuncianteBO = new AnuncianteBO();
            int linhaselecionada = this.tblAnunciantes.getSelectedRow();
            anuncianteSelecionado = this.anunciantes.get(linhaselecionada);
            TelaCadastroAnunciante telaCadastroAnunciante = new TelaCadastroAnunciante(anuncianteSelecionado,"editar");
            telaCadastroAnunciante.setVisible(true);
            this.exibirDadosTabela();

            anuncianteBO.alterar(anuncianteSelecionado);
        } catch (ArrayIndexOutOfBoundsException aiobe) {
            String mensagem = "Nenhum Anunciante selecionado";
            String titulo = "Erro";
            exibirMensagemErro(mensagem, titulo);
        } catch (SQLException ex) {
            Logger.getLogger(ListarAnunciante.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.exibirDadosTabela();
        }
                                            

    
    }//GEN-LAST:event_btEditarActionPerformed

    private void btRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioActionPerformed
        
        try {
            String arquivoRelatorio = System.getProperty("user.dir")
                    + "/Relatorios/RelatorioAnu.jasper";
               
            Map<String, Object> paramentros = new HashMap<String, Object>();

            JRBeanCollectionDataSource fonteDados
                    = new JRBeanCollectionDataSource(this.anunciantes);

            JasperPrint relatorioGerado = JasperFillManager.fillReport(arquivoRelatorio, paramentros, fonteDados);

            JasperViewer telaExibicaoRelatorio
                    = new JasperViewer(relatorioGerado, false);
            telaExibicaoRelatorio.setTitle("Relatório de Anunciantes");
            telaExibicaoRelatorio.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(ListarAnunciante.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao exibir relatório.", "Erro", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarAnunciante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarAnunciante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarAnunciante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarAnunciante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarAnunciante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JInternalFrame pnListarAnunciante;
    private javax.swing.JTable tblAnunciantes;
    private javax.swing.JLabel txtListarAnunciante;
    // End of variables declaration//GEN-END:variables

    class ModeloDadosAnunciantes extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return anunciantes.size();
        }

        @Override
        public String getColumnName(int column) {
            if (column == 0) {
                return "Id Anunciante";
            } else if (column == 1) {
                return "NOME";
            } else if (column == 2) {
                return "CPF";
            } else if (column == 3) {
                return "TELEFONE";
            } else if (column == 4) {
                return "RUA";
            } else if (column == 5) {
                return "BAIRRO";
            } else if (column == 6) {
                return "CIDADE";
            } else {
                return "NUMRESIDENCIA";
            }
        }

        @Override
        public int getColumnCount() {
            return 8;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Anunciante anunciante = anunciantes.get(rowIndex);
            if (columnIndex == 0) {
                return anunciante.getIdAnunciante();
            } else if (columnIndex == 1) {
                return anunciante.getNome();
            } else if (columnIndex == 2) {
                return anunciante.getCpf();
            } else if (columnIndex == 3) {
                return anunciante.getTelefone();
            } else if (columnIndex == 4) {
                return anunciante.getRua();
            } else if (columnIndex == 5) {
                return anunciante.getBairro();

            } else if (columnIndex == 6) {
                return anunciante.getCidade();

            } else {
                return anunciante.getNumResidencia();

            }

        }

    }
}
