/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.Radio.Apresentacao;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author WellisonTiago
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListarLocutores.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ListarLocutores.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ListarLocutores.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ListarLocutores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    ImageIcon icon = new ImageIcon("C:\\Users\\WellisonTiago\\Documents\\NetBeansProjects\\Radio\\Imagens\\Radio.jpg");
    JLabel label = new JLabel(icon);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        TxtImagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastrar = new javax.swing.JMenu();
        mnCadasAnunciante = new javax.swing.JMenuItem();
        mnCadastrarLocutor = new javax.swing.JMenuItem();
        MnCadastroAnuncio = new javax.swing.JMenuItem();
        MnCadastroAdmin = new javax.swing.JMenuItem();
        MnCadastrarMensalidade = new javax.swing.JMenuItem();
        MnCadastrarPrograma = new javax.swing.JMenuItem();
        MnCadastrarLocutor_Programa = new javax.swing.JMenuItem();
        mnCadasProgramaAnuncio = new javax.swing.JMenuItem();
        mnListar = new javax.swing.JMenu();
        mnListarAnunciante = new javax.swing.JMenuItem();
        mnListarLocutor = new javax.swing.JMenuItem();
        mnListarAnuncios = new javax.swing.JMenuItem();
        mnMensalidade = new javax.swing.JMenuItem();
        mnAdminstradores = new javax.swing.JMenuItem();
        mnListarProgramas = new javax.swing.JMenuItem();
        mnValor = new javax.swing.JMenu();
        MnRendaMes = new javax.swing.JMenuItem();
        mnRendaAno = new javax.swing.JMenuItem();
        mnRalatorios = new javax.swing.JMenu();
        mnRelatorioAnu = new javax.swing.JMenuItem();
        mnRelatorioLocutores = new javax.swing.JMenuItem();
        mnGraficos = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WT Radio");

        TxtImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/Radio/Apresentacao/imagens/ecd1cf562be587381892e86e5964a692.jpg"))); // NOI18N

        mnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/Radio/Apresentacao/imagens/icone_usuario_novo.png"))); // NOI18N
        mnCadastrar.setText("Cadastar");

        mnCadasAnunciante.setText("Cadastar Anunciante");
        mnCadasAnunciante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadasAnuncianteActionPerformed(evt);
            }
        });
        mnCadastrar.add(mnCadasAnunciante);

        mnCadastrarLocutor.setText("Cadastar Locutor");
        mnCadastrarLocutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarLocutorActionPerformed(evt);
            }
        });
        mnCadastrar.add(mnCadastrarLocutor);

        MnCadastroAnuncio.setText("Cadastrar Anuncio");
        MnCadastroAnuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroAnuncioActionPerformed(evt);
            }
        });
        mnCadastrar.add(MnCadastroAnuncio);

        MnCadastroAdmin.setText("Cadastrar Adminstrador");
        MnCadastroAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroAdminActionPerformed(evt);
            }
        });
        mnCadastrar.add(MnCadastroAdmin);

        MnCadastrarMensalidade.setText("Cadastrar Mensalidade");
        MnCadastrarMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastrarMensalidadeActionPerformed(evt);
            }
        });
        mnCadastrar.add(MnCadastrarMensalidade);

        MnCadastrarPrograma.setText("Cadastrar Programa");
        MnCadastrarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastrarProgramaActionPerformed(evt);
            }
        });
        mnCadastrar.add(MnCadastrarPrograma);

        MnCadastrarLocutor_Programa.setText("Cadastrar Locutor_Programa");
        MnCadastrarLocutor_Programa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastrarLocutor_ProgramaActionPerformed(evt);
            }
        });
        mnCadastrar.add(MnCadastrarLocutor_Programa);

        mnCadasProgramaAnuncio.setText("Cadastrar Programa_Anunciante");
        mnCadasProgramaAnuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadasProgramaAnuncioActionPerformed(evt);
            }
        });
        mnCadastrar.add(mnCadasProgramaAnuncio);

        jMenuBar1.add(mnCadastrar);

        mnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/Radio/Apresentacao/imagens/novoTopicoIcone.png"))); // NOI18N
        mnListar.setText("Listar");

        mnListarAnunciante.setText("Listar Anunciante");
        mnListarAnunciante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListarAnuncianteActionPerformed(evt);
            }
        });
        mnListar.add(mnListarAnunciante);

        mnListarLocutor.setText("Listar Locutor");
        mnListarLocutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListarLocutorActionPerformed(evt);
            }
        });
        mnListar.add(mnListarLocutor);

        mnListarAnuncios.setText("Listar Anuncios");
        mnListarAnuncios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListarAnunciosActionPerformed(evt);
            }
        });
        mnListar.add(mnListarAnuncios);

        mnMensalidade.setText("Listar Mensalidade");
        mnMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMensalidadeActionPerformed(evt);
            }
        });
        mnListar.add(mnMensalidade);

        mnAdminstradores.setText("Listar Adminstradores");
        mnAdminstradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAdminstradoresActionPerformed(evt);
            }
        });
        mnListar.add(mnAdminstradores);

        mnListarProgramas.setText("Listar Programas");
        mnListarProgramas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListarProgramasActionPerformed(evt);
            }
        });
        mnListar.add(mnListarProgramas);

        jMenuBar1.add(mnListar);

        mnValor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/Radio/Apresentacao/imagens/saldo.jpg"))); // NOI18N
        mnValor.setText("Renda");

        MnRendaMes.setText("Renda Por Mês");
        MnRendaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRendaMesActionPerformed(evt);
            }
        });
        mnValor.add(MnRendaMes);

        mnRendaAno.setText("Renda por Ano");
        mnRendaAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRendaAnoActionPerformed(evt);
            }
        });
        mnValor.add(mnRendaAno);

        jMenuBar1.add(mnValor);

        mnRalatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/Radio/Apresentacao/imagens/icone_relatorio.gif"))); // NOI18N
        mnRalatorios.setText("Relatórios");

        mnRelatorioAnu.setText("Relatório Anunciantes");
        mnRelatorioAnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelatorioAnuActionPerformed(evt);
            }
        });
        mnRalatorios.add(mnRelatorioAnu);

        mnRelatorioLocutores.setText("Relatório Locutores");
        mnRelatorioLocutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelatorioLocutoresActionPerformed(evt);
            }
        });
        mnRalatorios.add(mnRelatorioLocutores);

        jMenuBar1.add(mnRalatorios);

        mnGraficos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/Radio/Apresentacao/imagens/23_1.png"))); // NOI18N
        mnGraficos.setText("Gráficos");
        jMenuBar1.add(mnGraficos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtImagem)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtImagem)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadasAnuncianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadasAnuncianteActionPerformed
        // TODO add your handling code here:

        TelaCadastroAnunciante c = new TelaCadastroAnunciante(null, "cadastro");
        c.setVisible(true);
    }//GEN-LAST:event_mnCadasAnuncianteActionPerformed

    private void mnCadastrarLocutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarLocutorActionPerformed
        // TODO add your handling code here:

        TelaLocutor c = new TelaLocutor(null, "cadastro");
        c.setVisible(true);
    }//GEN-LAST:event_mnCadastrarLocutorActionPerformed

    private void MnCadastroAnuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroAnuncioActionPerformed
        // TODO add your handling code here:
        TelaCadastroAnuncio c = new TelaCadastroAnuncio(null, "cadastro");
        c.setVisible(true);

    }//GEN-LAST:event_MnCadastroAnuncioActionPerformed

    private void MnCadastroAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroAdminActionPerformed
        CadastroAdmin c = new CadastroAdmin(null, "cadastro");
        c.setVisible(true);

    }//GEN-LAST:event_MnCadastroAdminActionPerformed

    private void MnCadastrarMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastrarMensalidadeActionPerformed
        TelaCadastroMensalidade c = new TelaCadastroMensalidade(null, "cadastro");
        c.setVisible(true);
    }//GEN-LAST:event_MnCadastrarMensalidadeActionPerformed

    private void MnCadastrarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastrarProgramaActionPerformed
        TelaCadastroPrograma c = new TelaCadastroPrograma(null, "cadastro");
        c.setVisible(true);
    }//GEN-LAST:event_MnCadastrarProgramaActionPerformed

    private void MnCadastrarLocutor_ProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastrarLocutor_ProgramaActionPerformed
        TelaCadastroLocutor_Programa c = new TelaCadastroLocutor_Programa();
        c.setVisible(true);
    }//GEN-LAST:event_MnCadastrarLocutor_ProgramaActionPerformed

    private void mnCadasProgramaAnuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadasProgramaAnuncioActionPerformed
        TelaCadastroPrograma_Anuncio c = new TelaCadastroPrograma_Anuncio();
        c.setVisible(true);
    }//GEN-LAST:event_mnCadasProgramaAnuncioActionPerformed

    private void MnRendaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRendaMesActionPerformed
         ValorPorAnoMes c = new  ValorPorAnoMes ();
        c.setVisible(true);
    }//GEN-LAST:event_MnRendaMesActionPerformed

    private void mnRendaAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRendaAnoActionPerformed
       ValorPorAno c = new ValorPorAno();
        c.setVisible(true);
    }//GEN-LAST:event_mnRendaAnoActionPerformed

    private void mnListarProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListarProgramasActionPerformed
        ListarProgramas c = new ListarProgramas();
        c.setVisible(true);
    }//GEN-LAST:event_mnListarProgramasActionPerformed

    private void mnAdminstradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAdminstradoresActionPerformed
        ListarAdminstradores c = new ListarAdminstradores();
        c.setVisible(true);
    }//GEN-LAST:event_mnAdminstradoresActionPerformed

    private void mnMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMensalidadeActionPerformed
        ListarMensalidades c = new ListarMensalidades();
        c.setVisible(true);
    }//GEN-LAST:event_mnMensalidadeActionPerformed

    private void mnListarAnunciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListarAnunciosActionPerformed

        // TODO add your handling code here
        ListarAnuncios c = new ListarAnuncios();
        c.setVisible(true);
    }//GEN-LAST:event_mnListarAnunciosActionPerformed

    private void mnListarLocutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListarLocutorActionPerformed
        // TODO add your handling code here:
        ListarLocutores c = new ListarLocutores();
        c.setVisible(true);
    }//GEN-LAST:event_mnListarLocutorActionPerformed

    private void mnListarAnuncianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListarAnuncianteActionPerformed
        // TODO add your handling code here:
        ListarAnunciante c = new ListarAnunciante();
        c.setVisible(true);
    }//GEN-LAST:event_mnListarAnuncianteActionPerformed

    private void mnRelatorioAnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelatorioAnuActionPerformed
       RelatorioAnunciante c = new RelatorioAnunciante ();
       c.setVisible(true);
    }//GEN-LAST:event_mnRelatorioAnuActionPerformed

    private void mnRelatorioLocutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelatorioLocutoresActionPerformed
        RelatorioLocutores c = new RelatorioLocutores ();
         c.setVisible(true);
    }//GEN-LAST:event_mnRelatorioLocutoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnCadastrarLocutor_Programa;
    private javax.swing.JMenuItem MnCadastrarMensalidade;
    private javax.swing.JMenuItem MnCadastrarPrograma;
    private javax.swing.JMenuItem MnCadastroAdmin;
    private javax.swing.JMenuItem MnCadastroAnuncio;
    private javax.swing.JMenuItem MnRendaMes;
    private javax.swing.JLabel TxtImagem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mnAdminstradores;
    private javax.swing.JMenuItem mnCadasAnunciante;
    private javax.swing.JMenuItem mnCadasProgramaAnuncio;
    private javax.swing.JMenu mnCadastrar;
    private javax.swing.JMenuItem mnCadastrarLocutor;
    private javax.swing.JMenu mnGraficos;
    private javax.swing.JMenu mnListar;
    private javax.swing.JMenuItem mnListarAnunciante;
    private javax.swing.JMenuItem mnListarAnuncios;
    private javax.swing.JMenuItem mnListarLocutor;
    private javax.swing.JMenuItem mnListarProgramas;
    private javax.swing.JMenuItem mnMensalidade;
    private javax.swing.JMenu mnRalatorios;
    private javax.swing.JMenuItem mnRelatorioAnu;
    private javax.swing.JMenuItem mnRelatorioLocutores;
    private javax.swing.JMenuItem mnRendaAno;
    private javax.swing.JMenu mnValor;
    // End of variables declaration//GEN-END:variables
}
