/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.Radio.Apresentacao;

import br.edu.ifnmg.Radio.Entidade.Anuncio;
import br.edu.ifnmg.Radio.Negocio.AnuncioBO;
import br.edu.ifnmg.Radio.Entidade.Anunciante;
import br.edu.ifnmg.Radio.Negocio.AnuncianteBO;
import br.edu.ifnmg.Radio.Negocio.Exception.NenhumAnuncianteCadastradoException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.chart.PieChart.Data;
import javax.swing.JOptionPane;

/**
 *
 * @author WellisonTiago
 */
public class TelaCadastroAnuncio extends javax.swing.JFrame {

    private Anuncio anuncio;
    List<Anunciante> Anunciantes;
    int posicaoAnuncianteSelecionado;
    Anunciante anunciante = new Anunciante();
    List<Anunciante> listaAnunciante = new ArrayList<Anunciante>();

    /**
     * Creates new form TelaCadastroAnuncio
     */
    public TelaCadastroAnuncio(Anuncio anuncio, String tipoTela) {
        initComponents();
        this.anuncio = anuncio;
        this.carregarComoBox();
        if (tipoTela.equals("cadastro")) {
            this.btAlterar.setVisible(false);
            this.lbAlterarAnuncio.setVisible(false);
            this.btAdicionar.setVisible(true);
            this.lbAnuncio.setVisible(true);
        } else {
            this.txtDescricao.setText(anuncio.getDescricao());
            this.txtQaunPorDia.setText(Integer.toString(anuncio.getQuanPorDia()));
            this.txtDataTerminio.setText(anuncio.getDataFormatadaEncerramento());
            this.btAlterar.setVisible(true);
            this.lbAlterarAnuncio.setVisible(true);
            this.btAdicionar.setVisible(false);
            this.lbAnuncio.setVisible(false);

        }
    }

    //int linhaselecionada = this.cmbAnunciante.getSelectedIndex();
    private void lerDadosTela() throws ParseException {
        anuncio = new Anuncio();

        anuncio.setDescricao(txtDescricao.getText().trim());
        String quantidade = txtQaunPorDia.getText().trim();
        anuncio.setQuanPorDia(Integer.parseInt(quantidade));
        Date data = new Date(System.currentTimeMillis());
        this.anuncio.setInicoAnuncio(data);

        SimpleDateFormat formata = new SimpleDateFormat("dd/MM/yyyy");

        String form = "dd/MM/yyyy";
        Date date = new SimpleDateFormat(form).parse(txtDataTerminio.getText().trim());

        anuncio.setEncerramentoAnuncio(date);

        posicaoAnuncianteSelecionado = cmbAnunciante.getSelectedIndex();
        anunciante = listaAnunciante.get(posicaoAnuncianteSelecionado);
        anuncio.setIdAnunciante(anunciante.getIdAnunciante());

    }

    private void limparCamposTela() {

        this.txtDescricao.setText("");
        this.txtQaunPorDia.setText("");
        this.txtDataTerminio.setText("");

    }

    private void exibirMensagemSucesso(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Cadastro de Anuncio", JOptionPane.INFORMATION_MESSAGE);

    }

    private void exibirMensagemErro(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Erro ao cadastrar Anuncio", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFanuncio = new javax.swing.JLayeredPane();
        lbAnuncio = new javax.swing.JLabel();
        lbDescrição = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lbQuantPorDia = new javax.swing.JLabel();
        txtQaunPorDia = new javax.swing.JTextField();
        lbDataTerminio = new javax.swing.JLabel();
        txtDataTerminio = new javax.swing.JTextField();
        cmbAnunciante = new javax.swing.JComboBox();
        lbAnunciante = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        lbAlterarAnuncio = new javax.swing.JLabel();
        btAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JFanuncio.setBackground(new java.awt.Color(51, 153, 0));

        lbAnuncio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbAnuncio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAnuncio.setText("Cadastrar Anuncio");

        lbDescrição.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDescrição.setText("Descrição:");

        lbQuantPorDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbQuantPorDia.setText("Qauntidade de reprodução por dia :");

        txtQaunPorDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQaunPorDiaActionPerformed(evt);
            }
        });

        lbDataTerminio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDataTerminio.setText("Data Terminio:");

        cmbAnunciante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAnunciante.setSelectedItem(anunciante.getIdAnunciante());
        cmbAnunciante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAnuncianteActionPerformed(evt);
            }
        });

        lbAnunciante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbAnunciante.setText("Anunciante:");

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/Radio/Apresentacao/imagens/save31.png"))); // NOI18N
        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        lbAlterarAnuncio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbAlterarAnuncio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAlterarAnuncio.setText("Alterar Anuncio");

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/Radio/Apresentacao/imagens/edit5.png"))); // NOI18N
        btAlterar.setText("Altarar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JFanuncioLayout = new javax.swing.GroupLayout(JFanuncio);
        JFanuncio.setLayout(JFanuncioLayout);
        JFanuncioLayout.setHorizontalGroup(
            JFanuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFanuncioLayout.createSequentialGroup()
                .addGroup(JFanuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JFanuncioLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lbDataTerminio)
                        .addGroup(JFanuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JFanuncioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbAnunciante, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(JFanuncioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataTerminio, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(JFanuncioLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(188, 188, 188))
            .addGroup(JFanuncioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JFanuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JFanuncioLayout.createSequentialGroup()
                        .addComponent(lbDescrição)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(202, Short.MAX_VALUE))
                    .addGroup(JFanuncioLayout.createSequentialGroup()
                        .addComponent(lbQuantPorDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQaunPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbAnunciante)
                        .addGap(254, 254, 254))))
            .addComponent(lbAnuncio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbAlterarAnuncio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JFanuncioLayout.setVerticalGroup(
            JFanuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFanuncioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAnuncio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAlterarAnuncio)
                .addGap(33, 33, 33)
                .addGroup(JFanuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescrição)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JFanuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JFanuncioLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(JFanuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAnunciante)
                            .addComponent(lbQuantPorDia)
                            .addComponent(txtQaunPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAnunciante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(JFanuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JFanuncioLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(JFanuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDataTerminio)
                            .addComponent(txtDataTerminio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
        );
        JFanuncio.setLayer(lbAnuncio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JFanuncio.setLayer(lbDescrição, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JFanuncio.setLayer(txtDescricao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JFanuncio.setLayer(lbQuantPorDia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JFanuncio.setLayer(txtQaunPorDia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JFanuncio.setLayer(lbDataTerminio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JFanuncio.setLayer(txtDataTerminio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JFanuncio.setLayer(cmbAnunciante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JFanuncio.setLayer(lbAnunciante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JFanuncio.setLayer(btAdicionar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JFanuncio.setLayer(lbAlterarAnuncio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JFanuncio.setLayer(btAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JFanuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JFanuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQaunPorDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQaunPorDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQaunPorDiaActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            lerDadosTela();
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastroAnunciante.class.getName()).log(Level.SEVERE, null, ex);
        }

        AnuncioBO anuncioBO = new AnuncioBO();

        try {
            anuncioBO.criar(anuncio);
            String mensagem = "Anuncio Cadastrado com Sucesso.";
            exibirMensagemSucesso(mensagem);
            this.limparCamposTela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroAnuncio.class.getName()).log(Level.SEVERE, null, ex);

        } catch (NenhumAnuncianteCadastradoException e) {
            String mensagem = "Erro ao cadastrar Anuncio ! Nenhum Anunciante Cadastardo.";
            this.exibirMensagemErro(mensagem);
        } catch (Exception e) {
            String mensagem = "Erro desconhecido. Entre em contato com o administrador do sistema.";
            this.exibirMensagemErro(mensagem);
            this.limparCamposTela();
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    public void carregarComoBox() {

        AnuncianteBO anuncianteBO = new AnuncianteBO();
        try {
            listaAnunciante = anuncianteBO.buscarTodos();

        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroAnuncio.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbAnunciante.removeAllItems();
        int linhaselecionada = this.cmbAnunciante.getSelectedIndex();
        for (int registro = 0; registro < listaAnunciante.size(); registro++) {
            //  System.out.println(listaAnunciante);
            anunciante = listaAnunciante.get(registro);
            cmbAnunciante.addItem(anunciante.getNome());
            // posicaoAnuncianteSelecionado = cmbAnunciante.getSelectedIndex();
        }
    }
    private void cmbAnuncianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnuncianteActionPerformed

        posicaoAnuncianteSelecionado = cmbAnunciante.getSelectedIndex();
        System.out.println(posicaoAnuncianteSelecionado);
        cmbAnunciante.setSelectedItem(anunciante.getIdAnunciante());
    }//GEN-LAST:event_cmbAnuncianteActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        try {

            AnuncioBO anuncioBO = new AnuncioBO();

            String form = "dd/MM/yyyy";
            Date date = new SimpleDateFormat(form).parse(txtDataTerminio.getText().trim());
            this.anuncio.setEncerramentoAnuncio(date);
            this.anuncio.setDescricao(txtDescricao.getText().trim());
            String quantidade = txtQaunPorDia.getText().trim();
            this.anuncio.setQuanPorDia(Integer.parseInt(quantidade));
            posicaoAnuncianteSelecionado = cmbAnunciante.getSelectedIndex();
            anunciante = listaAnunciante.get(posicaoAnuncianteSelecionado);
            anuncio.setIdAnunciante(anunciante.getIdAnunciante());

            anuncioBO.alterar(this.anuncio);

            this.exibirMensagemSucesso("Anuncio Alterado");
            this.limparCamposTela();

        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroAnuncio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastroAnuncio.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.dispose();
            // TODO add your handling code here
            ListarAnuncios c = new ListarAnuncios();
            c.setVisible(true);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane JFanuncio;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JComboBox cmbAnunciante;
    private javax.swing.JLabel lbAlterarAnuncio;
    private javax.swing.JLabel lbAnunciante;
    private javax.swing.JLabel lbAnuncio;
    private javax.swing.JLabel lbDataTerminio;
    private javax.swing.JLabel lbDescrição;
    private javax.swing.JLabel lbQuantPorDia;
    private javax.swing.JTextField txtDataTerminio;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQaunPorDia;
    // End of variables declaration//GEN-END:variables
}
